build_vars:
  NAME: omp-backend
  GIT_URL: https://github.com/rht-labs/open-management-portal-backend.git
  GIT_REF: master
  OUTPUT_IMAGE_NAME: omp-backend
  OUTPUT_IMAGE_TAG: latest
  BUILDER_IMAGE_NAME: registry.redhat.io/openjdk/openjdk-8-rhel8
  BUILDER_IMAGE_TAG: 1.1
  BUILDER_IMAGE_PULL_SECRET: builder-image-pull-secret

deploy_vars:
  NAME: omp-backend
  IMAGE_NAME: omp-backend
  IMAGE_TAG: latest
  JWT_PUBLIC_KEY_URL: http://sso-cluster-internal:8080/auth/realms/omp/protocol/openid-connect/certs
  GIT_REPO_URL: git@gitlab.com:my-org/omp-repo.git
  GIT_PRIVATE_KEY_PATH: /identity/ssh-privatekey
  GIT_SECRET_NAME: git-key

openshift_cluster_content:
- object: omp-backend
  content:
# Uncomment this if you would like to define your image pull secret here, and then DO NOT push this back to a public repository.
#  - name: image-pull-secret
#    file: '{{ inventory_dir }}/../files/image-pull-secret.yml'
# Uncomment this if you would like to define your SSH secret here, and then DO NOT push this back to a public repository.
#  - name: ssh-secret
#    file: '{{ inventory_dir }}/../files/ssh-secret.yml'
  - name: build
    template: '{{ inventory_dir }}/../templates/build.yml'
    params_from_vars: '{{ build_vars }}'
  - name: deployment
    template: '{{ inventory_dir }}/../templates/deploy.yml'
    params_from_vars: '{{ deploy_vars }}'