name: Java CI

on:
- push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 13.0.1
    - name: Build with Maven & Quarkus
      run: mvn test
    - uses: jacobsee/s2i-github-action@master
      with:
        base: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
        output_image: quay.io/rht-labs/omp-backend:latest
        image_push_registry: quay.io
        image_push_username: ${{ secrets.QUAY_USERNAME }}
        image_push_password: ${{ secrets.QUAY_PASSWORD }}
